BibliothecaDAO/realms-contracts

- contracts/nft_marketplace/bibliotheca_marketplace.cairo
Dear Lords,
I've been browsing the contracts and noticed that the `status` field in the `Trade` struct could be expressed as a [struct enum](https://hackmd.io/@RoboTeddy/BJZFu56wF#Struct-enum-pattern). This PR does just that. Feel free to close it if you don't feel like it makes sense.
May the sun never set on your realms. 👑
> refactor: TradeStatus struct enum

- contracts/l2/minigame/01_TowerDefence.cairo
- contracts/l2/minigame/02_TowerDefenceStorage.cairo
- contracts/l2/minigame/utils/interfaces.cairo
- contracts/l2/tokens/ERC20.cairo
- contracts/l2/tokens/IERC1155.cairo
- contracts/l2/tokens/IERC20.cairo
- testing/l2/minigame/01_TowerDefence_test.py
- testing/l2/utils/string.py
- Attack/shield wall actions
- Reward pools
> Attack/shield wall, reward pools

- contracts/settling_game/readme.md
This PR corrects some minor mistakes in the section about packing data. I hope it's more clear and easier to understand now. There's also some small style changes here and there...
> doc: packing section update

- testing/l2/conftest.py
As you know, there's been a ton of changes with 0.7.0, one of which is that `StarknetContract` from the testing module now takes a [`deploy_execution_info` argument](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/testing/contract.py#L53), which breaks the test setup in `conftest.py`. This PR fixes that.
> fix: making conftest work with cairo-lang v0.7.0

- contracts/L1-Solidity/README.md
- contracts/desiege/README.md
- contracts/exchange/README.md
- contracts/game_utils/README.md
- contracts/loot/README.md
- contracts/nft_marketplace/README.md
- contracts/openzeppelin/README.md
- contracts/settling_game/README.md
- contracts/token/README.md
- contracts/utils/README.md
Final adjustments to README.md's:
* Added TODO to any areas I could find with missing info
* Moved shared table (Realms repo's) to the main README and linked to it from the bottom of each sub-directory README.
> Added todos for unfilled sections

- .github/workflows/test.yaml
- contracts/settling_game/Arbiter.cairo
- contracts/settling_game/L01_Settling.cairo
- contracts/settling_game/L02_Resources.cairo
- contracts/settling_game/L03_Buildings.cairo
- contracts/settling_game/L04_Calculator.cairo
- contracts/settling_game/S01_Settling.cairo
- contracts/settling_game/S02_Resources.cairo
- contracts/settling_game/S03_Buildings.cairo
- contracts/settling_game/TemplateModule.cairo
- contracts/settling_game/interfaces/imodules.cairo
Unifies interfaces under `settling_game/interfaces` dir
> refactor: module interfaces location

- realms_cli/README.md
Restructured the README a little bit and added Docker setup.
> add Docker setup to README

- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/library/library_combat.cairo
- tests/settling_game/06_combat_test.py
- tests/settling_game/library_combat_tests.cairo
> fix: squad building

- contracts/settling_game/library/library_combat.cairo
- tests/settling_game/library_combat_tests.cairo
I learnt some Cairo black magic and applied it to the combat library. This bring quite serious optimization - `squad_to_array` goes (roughly) from 3244 steps to 1442 and `array_to_squad` from 1124 to 631 💥
> dev: combat library optimizations

- contracts/settling_game/L06_Combat.cairo
- tests/conftest.py
- tests/settling_game/06_combat_test.py
- tests/settling_game/L06_Combat_tests.cairo
- tests/settling_game/game_structs.py
Fixes a bug in `load_troop_costs`. Adds test for it as well.
> fix(combat): load_troop_costs

- .github/workflows/docker.yaml
Added ability to manually trigger docker github actions workflow
> Added ability to manually trigger docker github actions workflow

- Dockerfile
Add protostar & foundry to Dockerfile for https://github.com/BibliothecaForAdventurers/realms-contracts/issues/145
> add protostar and foundry to Dockerfile

- .github/workflows/docker.yaml
- .github/workflows/docker_test.yaml
Add GitHub action to automate testing via Docker
> Add GH action to automate testing via Docker

- .gitmodules
- contracts/settling_game/L04_Calculator.cairo
- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/library/library_combat.cairo
- contracts/settling_game/library/library_module.cairo
- contracts/settling_game/utils/game_structs.cairo
- protostar.toml
- pytest.ini
- tests/protostar/settling_game/combat/test_combat.cairo
- tests/protostar/settling_game/combat/test_combat_logic.cairo
- tests/protostar/settling_game/combat/test_library_combat.cairo
- tests/protostar/settling_game/combat/utils.py
- tests/pytest/conftest.py
- tests/pytest/settling_game/06_combat_test.py
- tests/pytest/settling_game/L06_Combat_tests.cairo
- tests/pytest/settling_game/game_structs.py
- tests/pytest/settling_game/library_combat_tests.cairo
This PR introduces the new combat goodies.
Summary of changes:
* new `TroopId`s
* new `TroopType`s
* new `building` property inside the `Troop` struct
* a Troop's `defense` has been renamed to `armor`
* new `TroopProps` namespace which defines all the properties (constants) of a Troop - type, tier, building, agility, attack, armor, vitality, wisdom
* the namespace has been renamed from `COMBAT` to `Combat`
* there's no `PackedSquad` now, since a Squad now consists of 15 Troops (down from 25) which, when packed, fit inside a single `felt`
* there's only a single attack type now, whereas previously we had a attack vs. defense or agility vs. wisdom and the player had to decide which one to use at attack time
* new combat formula `((a.agility - d.agility) + a.attack * (dice_roll - d.armor) - …
> feat: updating combat to v2 spec

- contracts/settling_game/L02_Resources.cairo
- contracts/settling_game/L04_Calculator.cairo
- contracts/settling_game/interfaces/imodules.cairo
- contracts/settling_game/modules/settling/interface.cairo
PR adds an interface file for the settling module, as part of the migration to new module structure and as discussed in #157
> dev(settling): adding interface file

- contracts/settling_game/L02_Resources.cairo
- contracts/settling_game/L05_Wonders.cairo
- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/ModuleController.cairo
- contracts/settling_game/README.md
- contracts/settling_game/interfaces/imodules.cairo
- contracts/settling_game/modules/calculator/Calculator.cairo
- contracts/settling_game/modules/calculator/interface.cairo
- contracts/settling_game/modules/food/Food.cairo
- contracts/settling_game/utils/game_structs.cairo
- realms_cli/deploy/game_contracts.py
- realms_cli/deploy/init_game.py
- realms_cli/realms_cli/config.py
- realms_cli/realms_cli/player/calculator.py
- tests/pytest/conftest.py
Applies #157 to the Calculator module.
Also contains some traces of what I forgot to do in #159 😇
> refactor(calculator): new module structure

- contracts/settling_game/Arbiter.cairo
- contracts/settling_game/interfaces/imodules.cairo
- contracts/settling_game/utils/game_structs.cairo
- realms_cli/deploy/game_contracts.py
- realms_cli/deploy/init_game.py
- realms_cli/realms_cli/config.py
- tests/protostar/settling_game/resources/test_resources_logic.cairo
- tests/pytest/conftest.py
Removes traces of the L05_Wonders module from the code. Builds on #190 but if that's merged, this one can be merged to master as well.
> chore: remove wonders

- contracts/settling_game/Arbiter.cairo
- contracts/settling_game/ModuleController.cairo
- contracts/settling_game/README.md
- contracts/settling_game/interfaces/imodules.cairo
- contracts/settling_game/modules/buildings/Buildings.cairo
- contracts/settling_game/modules/buildings/interface.cairo
- contracts/settling_game/utils/game_structs.cairo
- realms_cli/deploy/game_contracts.py
- realms_cli/deploy/init_game.py
- realms_cli/deploy/set_costs.py
- realms_cli/realms_cli/config.py
- realms_cli/realms_cli/player/buildings.py
- tests/protostar/settling_game/resources/test_resources_logic.cairo
- tests/pytest/conftest.py
Does #157 to the buildings module.
> refactor: buildings module

- .gitignore
- scripts/setup_cli_env.sh
Fix for appended files if setup script is re-run or run after new account is deployed
> Fix for appended files if setup script is re-run or run after new account is deployed

- .devcontainer/devcontainer.json
- scripts/setup_cli_env.sh
Setup Script Improvements:
1. Adds starknet env vars to bashrc to persist across container restarts
2. Adds option to cleanly exit
Dev Container updates:
1. Run setup script on container start
> setup script improvements + auto-run on container launch

- scripts/setup_cli_env.sh
> temporarily remove ArgentX

- contracts/settling_game/modules/combat/Combat.cairo
- contracts/settling_game/utils/game_structs.cairo
> fixed camel case in ArmyData

- contracts/settling_game/modules/combat/Combat.cairo
- contracts/settling_game/modules/combat/L06_Combat.cairo
- contracts/settling_game/modules/resources/Resources.cairo
- contracts/settling_game/modules/resources/library.cairo
- contracts/settling_game/utils/constants.cairo
- tests/protostar/settling_game/resources/test_calculate_resources.cairo
starts #26 
Combat update only
> begins namespace update

- contracts/metadata/metadata.cairo
- tests/protostar/metadata/test_metadata.cairo
> chore: cleanup

- contracts/settling_game/tokens/Realms_ERC721_Mintable.cairo
- tests/protostar/metadata/test_metadata_logic.cairo
- remove name realm data shifting
- fix tests
> fix: order metadata

- scripts/setup_cli_env.sh
Updates setup cli script to check bashrc to see if it has already run. If it has already run, it exits without performing any changes
> fixes issue #255

- contracts/loot/adventurer/Adventurer.cairo
> resolves #286 by removing duplicate adventurer_balance declaration

- contracts/loot/loot/library.cairo
- tests/protostar/loot/loot/test_loot.cairo
This commit contains the skeleton and test cases for the work detailed in issue #289
> Part of #288 - Provides instructions for #289

- contracts/settling_game/modules/combat/Combat.cairo
**A generalisation of the initiate_combat entrypoint callable by allowed modules**
I am currently working on the Bastion module, which involves having armies combat outside of Realms.
The existing "initiate_combat" entrypoint of the Combat module has one constraint that only allows it to be called to attack Realms (verifies that the realm of defending army can be attacked). There are also consequences when attacker wins that are only applicable for that specific case (steals relic and pillages resources).
What I propose is to create **a new external function called "initiate_combat_approved_module"** callable by any approved module and containing combat logic applicable to any situation. The approved module would then have the responsibility to apply the extra conditions for combat and …
> feat Added more general combat function
