- .github/workflows/test.yaml
- bin/test
Trying to fix the test Github Action.
The [`pytest-xdist`](https://pypi.org/project/pytest-xdist/) plugin isn't available in the execution container, hence the failure. When using xdist, the `-s` flag for pytest doesn't have any effect, so removing that as well.
> fix: test GH action

- bin/compile_exchange
- bin/deploy_exchange
- bin/test
- contracts/exchange/Exchange_ERC20_1155.cairo
- contracts/exchange/README.md
- testing/l2/Exchange_ERC20_1155_test.py
- testing/l2/conftest.py
This is for the proposal outlined in Snapshot: 
https://snapshot.org/#/council.bibliotheca.eth/proposal/0x34a09597e73f3d45c0f2d8d5cac6dfb562add3adddaba72040ac688f8b60f580
Features:
* Buy / Sell across ERC20 / ERC1155 pairs
* One exchange supports all token ids across the ERC1155 contract
* Liquidity provider fees are customisable during deployment
* LP tokens are ERC1155 compliant so they are tradable etc
Considerations:
* `felt` vs `Uint256`. I've gone with Uint256 for all currency-related fields, felt for everything else. 
* The current ERC1155 implementation is not compliant with the ERC1155 spec as it does not support the `safeTransfer` callbacks. Due to this, the exchange contract must have unlimited approval on a token to use it. This is not so desirable from a gas or security …
> BIP-3 Exchange ERC20 ERC1155

- contracts/settling_game/L06_Combat.cairo
- contracts/utils/xoroshiro128_starstar.cairo
- testing/l2/L06_Combat_tests.cairo
- testing/l2/conftest.py
Following up on the outstanding TODOs in the combat module, this PR adds the xoroshiro PRNG as our "internal" contract that we will need to deploy on our own. Its address is then passed to the constructor of L06_Combat.
> dev(combat): adding internal prng

- .github/workflows/lint.yml
- requirements.txt
- tests/conftest.py
This PR adds a GH Action to lint *.cairo files. It also bumps cairo-lang to [v0.8.1](https://github.com/starkware-libs/cairo-lang/releases/tag/v0.8.1) which was released a couple of days ago and actually has significant changes to the formatter.
> ci: setup cairo linting, bump to cairo 0.8.1

- README.md
- contracts/settling_game/README.md
Added documentation about how to auth via your dev container and migrated the docs to the main README (along with a breadcrumb in the settling_game readme so people can find it easily). 
This should help new users of the project and make sure we don't try to maintain two versions of the docs about containers.
> docs: moved container documentation to the main readme.me issue #43

- .github/workflows/static_analysis.yml
Trail of Bits [just released](https://blog.trailofbits.com/2022/04/20/amarna-static-analysis-for-cairo-programs/) Amarna, a static analysis tool for Cairo (as is Slither for Solidity).
This PR adds a new CI job to run the analysis tool on our Cairo code.
> ci: adding Amarna static analysis for Cairo

- .gitignore
- openzeppelin/account/library.cairo
- tasks/deploy_account.ts
- tasks/helpers/index.ts
- Desiege needed a separate deployments directory when running scripts. Added support for `DEPLOYMENT_BASE` env var in a backwards compatible way so that this can be configured. Also added `ACCOUNT_NAME` env so multiple accounts can be deployed and used for further deployments.
- Refactored `tasks/helpers.ts` with more consistent account retrieval method, maintains backwards compatibility
Extras
- Added `node_modules` to gitignore since this repo also serves as a JS task exec environment
- The latest OZ Account contract had very small diff to remove a duplicated `@view` function for signature checking
> Deploy Enhancements & Account Management 

- Dockerfile
Add realms-contract repo to base Dockerfile and pip install cli to make it easier for newcomers to get started with the CLI.
> add realms-contract repo to base Dockerfile

- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/library/library_combat.cairo
- contracts/settling_game/utils/game_structs.cairo
- tests/settling_game/06_combat_test.py
- tests/settling_game/L06_Combat_tests.cairo
- tests/settling_game/game_structs.py
- tests/settling_game/library_combat_tests.cairo
As discussed in #107, this PR does only with using troop ID and vitality when packing it into a `PackedSquad`, dramatically decreasing the storage slots needed from 7 to 2 felts.
To do this, the `Troop` struct now also contains an `id` member.
Most combat library tests pass - those that don't (`test_run_combat_loop`, `test_attack` and `test_update_squad_in_realm`) fail because of the "external" ownership check.
> refactor: squad packing

- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/library/library_combat.cairo
- tests/settling_game/06_combat_test.py
- tests/settling_game/library_combat_tests.cairo
Adds `remove_troops_from_squad_in_realm` to provide a safe way how to remove troops from squad. Makes `update_squad_in_realm` internal. Other various fixes here and there.
> dev(combat): func to remove troops from squad

- contracts/settling_game/tokens/Lords_ERC20_Mintable.cairo
- contracts/settling_game/tokens/Realms_ERC721_Mintable.cairo
- contracts/settling_game/tokens/S_Realms_ERC721_Mintable.cairo
An example PR for #115.
Deals with [this](https://github.com/BibliothecaForAdventurers/realms-contracts/security/code-scanning/1752), [this](https://github.com/BibliothecaForAdventurers/realms-contracts/security/code-scanning/1751), and [this](https://github.com/BibliothecaForAdventurers/realms-contracts/security/code-scanning/1750) Amarna alerts. Also removes a `%builtins` directive as those are deprecated in newer Cairo versions.
> chore: fixing some Amarna alerts

- contracts/settling_game/L04_Calculator.cairo
- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/interfaces/imodules.cairo
This PR introduces a wall defense mechanism of a Realm. 
As a first round of an attack, the attacking squad receives damage from the defending Realm (the "wall"). The amount of hit points inflicted is based on the Realm population as in the range of 0 to 5 (inclusive). Can be easily tweak as necessary. There's no event emitted about this.
There's also some small fixes (var rename and broadening of `IL04_Calculator` interface), since I've been digging in those parts.
> Wall defence

- contracts/settling_game/L06_Combat.cairo
The combat loop was still passed the original attacking squad, not the one that already inflicted damage from breaching the wall. This PR fixes it.
> fix(combat): run combat loop with attacker after breaching wall

- contracts/settling_game/interfaces/s_realms_IERC721.cairo
I wanted to use the s_realms_ERC721 contract from another contracts but had to add `tokenByIndex` function in the interface. The PR adds this function with `tokenOfOwnerByIndex`
> add missing functions for s_realms interface

- contracts/exchange/Exchange_ERC20_1155.cairo
- contracts/exchange/library.cairo
- contracts/token/interfaces/IERC1155_Receiver.cairo
Ran `cairo-format -i` on the files to fix linting.
> chore: cairo lint fix

- contracts/settling_game/L02_Resources.cairo
- contracts/settling_game/L04_Calculator.cairo
- contracts/settling_game/ModuleController.cairo
- contracts/settling_game/README.md
- contracts/settling_game/interfaces/imodules.cairo
- contracts/settling_game/modules/settling/Settling.cairo
- contracts/settling_game/utils/game_structs.cairo
- realms_cli/deploy/game_contracts.py
- realms_cli/deploy/init_game.py
- realms_cli/realms_cli/config.py
- realms_cli/realms_cli/player/settle.py
- tasks/settling/game_actions/mint_realm_stake.ts
- tasks/settling/modules/01_deploy_settling.ts
Applies #157 to the Settling module.
There's still some traces of "L01" left, but it's in pieces of code which I believe are stale, not used anymore (e.g. .ts files in [`tasks/settling/modules/`](https://github.com/BibliothecaForAdventurers/realms-contracts/tree/main/tasks/settling/modules)).
> refactor(settling): new module structure

- contracts/settling_game/L06_Combat.cairo
- contracts/settling_game/modules/food/Food.cairo
- contracts/settling_game/utils/general.cairo
- tests/pytest/settling_game/06_combat_test.py
- tests/pytest/settling_game/utils/general_tests.cairo
This PR adds support to specify a quantity multiplier to an internal function that transforms `Cost` structs to token values. In non-convoluted speak, this means it's now easy to "buy 20 things" - just need the `Cost` struct of a thing and set `qty` to 20.
I've merged `calculate_cost` and `transform_costs_to_token_ids_values` to a single function called `transform_costs_to_tokens` and updated its use in combat and food modules.
> dev: adding multiplier argument when calculating cost tokens

- contracts/settling_game/ModuleController.cairo
- contracts/settling_game/tokens/Resources_ERC1155_Mintable_Burnable.cairo
- contracts/settling_game/tokens/S_Crypts_ERC721_Mintable.cairo
- contracts/settling_game/tokens/S_Realms_ERC721_Mintable.cairo
- contracts/settling_game/utils/game_structs.cairo
PR related to issue #162 
I have added `Module.only_approved()` to the token contracts asserting whether a permission is stored in `ModuleController.cairo` be called for `mint` and `burn` functions. This involved:
* Updating the token contracts
* Added `Module.only_approved()` to functions required
* Remove `Set_module_access` methods, this seems redundant as `ModuleController.cairo` constructor stores permissions.
* Update `ModuleController.cairo` with required permissions for tokens.\
* Update `game_structs.cairo` with module ids for token contracts starting from 1000
**Note:**
There are token contracts that aren't ever called from modules (e.g `Realms_ERC721_Mintable.cairo`). For these I have just left the current asserts (I assume you still want anyone to be able to mint a realm).
I …
> feat: Add token module permissions

- contracts/settling_game/tokens/Resources_ERC1155_Mintable_Burnable.cairo
- contracts/token/library.cairo
As discussed with @ponderingdemocritus, need to get the correct token URIs for the NFT contracts.
The resources had a single URI set in the constructor. I have now implemented a `setTokenURI` where an ID of the resource is mapped to the URI.
Changes:
* Update Resource contract
* Initializer no longer takes a URI input
* URI view method updated, convention similar to `ERC721` tokens
* `setTokenURI` method implemented, similar to `ERC721` tokens
* Update `ERC1155` library contract, abiding by conventions of openzeppelin `ERC721` library contract
**Note**:
`library.cairo` method `_set_token_uri` has an additional check in openzeppelin `ERC721` to check whether an account holds at least one of the `token_id`. I'm not sure this is necessary, nor makes sense for `ERC1155`.
Tests have not been …
> feat: Add token URIs logic to resources

- contracts/settling_game/modules/resources/interface.cairo
Looks like I forgot to add the module `interface.cairo` file in #186. This PR fixes it.
> dev(resources): adding missing interface file

- contracts/loot/adventurer/Adventurer.cairo
fix the updated state to item_address when set_loot
> fix: fix the updated state to item_address when set_loot

- contracts/settling_game/modules/combat/library.cairo
- contracts/settling_game/utils/game_structs.cairo
Follow up on #233 and #199.
Fixes case in `Army` and `ArmyStatistics` structs.
Also fixes a bug in computing remaining health of light infantry ([L544](https://github.com/BibliothecaForAdventurers/realms-contracts/compare/fix/case-in-combat?expand=1#diff-2857f115b76adf25645866adfaa8a026f9093fafe90b715245b85311a704e123R544))
> fix: struct case convention for Army and ArmyStatistics

- contracts/settling_game/modules/combat/Combat.cairo
- contracts/settling_game/modules/combat/library.cairo
- contracts/settling_game/utils/game_structs.cairo
This PR makes combat much more effective / cheaper in gas and also cleans up the combat library code a bunch.
The main thing the PR does is that it removes the packing & unpacking of `Army` between combat library calls. It's not necessary. The only packing and unpacking we need to do is when dealing with storage (either writing to or reading from). All internal (library) functions should work on unpacked values only. This rule applies to the whole codebase. It's much more effective this way.
I've also removed the unnecessary `defending_army_packed` parameter to `update_and_pack_army` (the function is now called `update_army`).
Should be merged after #234 as it builds on it.
> refactor: no packing inside lib

- contracts/settling_game/tokens/S_Realms_ERC721_Mintable.cairo
When you want a settled Realm NFT, you first settle your Realm NFT via `Settling.cairo` which will take your Realm and mint you an SRealm by calling `S_Realms_ERC721_Mintable::mint`:
```cairo
@external
func mint{pedersen_ptr: HashBuiltin*, syscall_ptr: felt*, range_check_ptr}(
to: felt, tokenId: Uint256
) {
Module.only_approved();
ERC721Enumerable._mint(to, tokenId);
return ();
}
```
This call `Module.only_aproved()`:
```cairo
func only_approved{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}() {
alloc_locals;
let (success) = _only_approved();
let (self) = check_self();
assert_not_zero(success + self);
return ();
}
```
which then call `_only_approved`:
```cairo
func _only_approved{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}() -> (
success: felt
) { …
```
> initialize controlle in S_Realms

- scripts/setup_cli_env.sh
Per #237 our setup script was corrupted by windows newline characters which is preventing bash from being able to run it.
> fixes #237

- contracts/settling_game/modules/example/library.cairo
- contracts/settling_game/modules/travel/Travel.cairo
- contracts/settling_game/tokens/Realms_ERC721_Mintable.cairo
- contracts/settling_game/tokens/S_Realms_ERC721_Mintable.cairo
I ran `cairo-format` on all .cairo files, this is the result. Should fix the lint action.
> chore: linting cairo files

- contracts/bridge/lords_l2.cairo
- contracts/settling_game/tokens/Lords_ERC20_Mintable.cairo
Updates the L2 $LORDS contract:
* uses more granular access control lib instead of ownable (this enables the L2 bridge contract to call `mint` and `burn_away`)
* introduces a new protected `burn_away` function that the L2 bridge calls when bridging $LORDS from L2 back to L1
* exposes `has_role`, `grant_role`, `revoke_role` and `renounce_role` functions from the `AccessControl` library so they are publicly available
* removes upgradability / proxy from the ERC20 token
* removes the initial supply and recipient from the constructor, as the only way how to get L2 $LORDS should be by bridging (though this can be overridden by the `admin` and I'm not sure it's a good idea)
> chore: update Lords ERC20

- contracts/settling_game/modules/resources/Resources.cairo
Removing an assert that could throw in the combat flow when there's nothing to raid. That would cause the whole combat TX to revert, which is not desirable.
> fix: dont throw when pillaging resources in combat loop

- contracts/loot/adventurer/Adventurer.cairo
Before fix:
```
$ nile compile /workspaces/realms-contracts/contracts/loot/adventurer/Adventurer.cairo
🔨 Compiling /workspaces/realms-contracts/contracts/loot/adventurer/Adventurer.cairo
/workspaces/realms-contracts/contracts/loot/adventurer/Adventurer.cairo:94:6: Found more than one storage variable with the same name ('adventurer_balance').
func adventurer_balance(tokenId: Uint256) -> (balance: Uint256) {
^****************^
/workspaces/realms-contracts/contracts/loot/adventurer/Adventurer.cairo:81:6: Note: another definition appears here.
func adventurer_balance(adventurer_token_id: Uint256) -> (balance: Uint256) {
^****************^
🛑 Failed to compile the following 1 contract:
/workspaces/realms-contracts/contracts/loot/adventurer/Adventurer.cairo
```
After fix:
```
$ nile compile …
```
> resolves #271: removes duplicate adventurer_balance

- contracts/settling_game/modules/travel/Travel.cairo
- tests/protostar/settling_game/travel/test_travel.cairo
**Allow approved modules to restrain an item from travelling**
I am currently working on the Bastion module, which needs to track the number of armies that are defending a bastion (a location on the map). 
Armies can travel in and out of the bastion using "travel" but they have to actively call a "defend" entrypoint to become a defender. This allows the Bastion Module to track the number of defenders of a bastion for example. Once an army becomes a defender, they should not be able to travel out of the bastion without removing themselves from the defense first. At the moment, the travel function allows any item to travel without constraint except when it is a defending army of a realm.  
What I propose is a general solution that adds a new storage_var in the Travel module called …
> feat Allow approved modules to forbid travel
